version: "3.8"

services:
  server:
    build: ./server
    ports:
    - "5001:5000"  # Change this line
    volumes:
      - ./server:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: